#!/bin/sh

DEFAULT_VERSION=v0.3.3

if test -d .git -o -f .git &&
	VN=$(git describe --tags --abbrev=4 --dirty 2>/dev/null)
then
	VN=$(echo "$VN" | sed 's/-/+/;s/\(.*\)-g/\1-/');
	VN=$(echo "$VN" | sed 's/-/./g');
else
	VN="$DEFAULT_VERSION"
fi

VN=$(expr "$VN" : v*'\(.*\)')
echo $VN
